name:                water-cooler
version:             0.1.0.0
github:              "githubuser/haskeleton"
license:             BSD2
author:              "Joshua Magee"
maintainer:          "magee.joshua@yahoo.com"
copyright:           "2018 Joshua Magee"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/haskeleton#readme>

dependencies:
- base >= 4.7 && < 5

library: 
  source-dirs: lib
  ghc-options:
    - -Wall
  dependencies:
    - aeson
    - aeson-pretty
    - bytestring
    - containers
    - directory
    - exceptions
    - filepath
    - gitrev
    - optional-args
    - path
    - QuickCheck
    - string-conversions
    - text
    - time

executables:
  water-cooler:
    main:                water-cooler.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - water-cooler
    - containers
    - directory
    - optional-args
    - optparse-applicative
    - text
    - time

tests:
  water-cooler-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - water-cooler
    - containers
    - directory
    - hspec
    - path
    - QuickCheck
    - time
